load("@io_bazel_rules_go//go:def.bzl", "go_test")
load("@rules_python//python:defs.bzl", "py_test")

    

go_test(
    name = "go_basic_test",
    srcs = ["go_basic_test.go"]
)

py_test(
    name="python_basic_test",
    srcs = ["python_basic_test.py"]
)