load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "flagutil",
    srcs = glob(["*.go"]),
    importpath = "github.com/zemnmez/quickcult/go/flag/flagutil",
    visibility = ["//visibility:public"],
)
