load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "ziputil",
    srcs = glob(["*.go"]),
    importpath = "github.com/zemnmez/quickcult/go/archive/zip/ziputil",
    visibility = ["//visibility:public"],
)
